### ISSUE TITLE
Add output for selected terraform version

### ISSUE THREAD

**Issue by chris3ware** [stv-io/action-tfswitch#2]
Hi, I've just started using this action in my workflow and it works very well. I've had to pass the terraform version installed via tfswitch to `$GITHUB_OUTPUT` for use with setup-terraform, like so:

```yaml
      - name: Setup tfswitch
        uses: stv-io/action-tfswitch@b6c5e07f48a6de1934acf5e9c67bd3b21423e9e1 # v1.0.0

      - name: Get Terraform Version
        id: terraform-version
        run: |
          tfswitch --chdir=terraform
          echo "VERSION=$(terraform --version | awk NR==1'{print substr($2, 2)}')" >> "$GITHUB_OUTPUT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
 ```
If I omit the echo to `$GITHUB_OUTPUT` and the `terraform_version` argument, then Setup Terraform proceeds to install the latest version:

<img width="790" alt="Screenshot 2023-11-24 at 12 21 39" src="https://github.com/stv-io/action-tfswitch/assets/36608309/493f8544-b497-48df-8134-b3b5e2b9f0ca">

I wondered if this was the expected behaviour, or if `action-tfswitch` could provide the appropriate version output for `setup_terraform`?
